[package]
name = "prisma-draw-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
strum = "0.24.1"
strum_macros = "0.24.3"
